/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cy_easynetwork_EasyNetwork */

#ifndef _Included_com_cy_easynetwork_EasyNetwork
#define _Included_com_cy_easynetwork_EasyNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cy_easynetwork_EasyNetwork
 * Method:    en_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cy_easynetwork_EasyNetwork_en_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_cy_easynetwork_EasyNetwork
 * Method:    en_final
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cy_easynetwork_EasyNetwork_en_1final
  (JNIEnv *, jclass);

/*
 * Class:     com_cy_easynetwork_EasyNetwork
 * Method:    en_start
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cy_easynetwork_EasyNetwork_en_1start
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_cy_easynetwork_EasyNetwork
 * Method:    en_stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cy_easynetwork_EasyNetwork_en_1stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
