/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cy_androidsdk_TestSdk */

#ifndef _Included_com_cy_androidsdk_TestSdk
#define _Included_com_cy_androidsdk_TestSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cy_androidsdk_TestSdk
 * Method:    func
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cy_androidsdk_TestSdk_func
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
